version: '3.8'

services:
  mysql:
    image: mysql:8.0.42
    container_name: setcollector-mysql
    environment:
      MYSQL_DATABASE: setcollector
      MYSQL_USER: setcollector
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - setcollector-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: setcollector-keycloak
    command: start-dev --import-realm
    ports:
      - "8181:8080"
    environment:
      KEYCLOAK_ADMIN: ADMIN
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB_USERNAME: setcollector
      KC_DB_PASSWORD: password
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    networks:
      - setcollector-network
    depends_on:
      mysql:
        condition: service_healthy

  backend:
    build:
      context: ../backend
      dockerfile: ../podman/backend/Dockerfile
    image: localhost/setcollector-backend:latest
    container_name: setcollector-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/setcollector?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: setcollector
      SPRING_DATASOURCE_PASSWORD: password
      KEYCLOAK_AUTH_SERVER_URL: http://setcollector-keycloak:8080
      KEYCLOAK_RESOURCE: setcollector-backend
      KEYCLOAK_PUBLIC_KEY: ${KEYCLOAK_PUBLIC_KEY}
    networks:
      - setcollector-network
    depends_on:
      mysql:
        condition: service_healthy
      keycloak:
        condition: service_started

  frontend:
    build:
      context: ..
      dockerfile: podman/frontend/Dockerfile
    image: localhost/setcollector-frontend:latest
    container_name: setcollector-frontend
    ports:
      - "5173:80"
    environment:
      VITE_API_URL: http://localhost:8080
      VITE_KEYCLOAK_URL: http://localhost:8181
      VITE_KEYCLOAK_REALM: setcollector-realm
      VITE_KEYCLOAK_CLIENT_ID: setcollector-frontend
    networks:
      - setcollector-network
    depends_on:
      - backend

networks:
  setcollector-network:
    name: setcollector-network

volumes:
  mysql_data:
    name: setcollector-mysql-data
  keycloak_realm:
    name: setcollector-keycloak-realm 