version: '3.8'
services:
  mysql:
    image: mysql:8.0.42
    container_name: setcollector-mysql
    environment:
      MYSQL_DATABASE: setcollector
      MYSQL_USER: setcollector
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      # Agregar base de datos para Keycloak
      MYSQL_DATABASE_KEYCLOAK: keycloak
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - setcollector-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    container_name: setcollector-keycloak
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_PORT: 3306
      DB_DATABASE: keycloak
      DB_USER: setcollector
      DB_PASSWORD: password
      # Configuraci贸n para resolver problemas de CORS y redirecciones
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: "8080"
      KC_HOSTNAME_URL: "http://localhost:8181"
      KC_HOSTNAME_ADMIN_URL: "http://localhost:8181"
      KC_PROXY: "edge"
      KC_CORS: "true"
      KC_CORS_ORIGINS: "http://localhost:5173,http://localhost:8080,http://localhost:3000,http://127.0.0.1:5173,http://setcollector-frontend,*"
      KC_CORS_METHODS: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
      KC_CORS_HEADERS: "Origin,Content-Type,Accept,Authorization,X-Requested-With,X-CSRF-Token,X-XSRF-Token,Cache-Control,Pragma,*"
      KC_CORS_EXPOSED_HEADERS: "Authorization,Content-Disposition,X-CSRF-Token,Content-Type,*"
      KC_CORS_ALLOW_CREDENTIALS: "true"
    ports:
      - "8181:8080"
    depends_on:
      - mysql
    networks:
      - setcollector-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    image: eclipse-temurin:21-jre-jammy
    container_name: setcollector-backend
    volumes:
      - ../backend/target/setcollectormtg-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    command: java -jar app.jar
    environment:
      # Variables de entorno para conexi贸n a MySQL
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/setcollector?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: setcollector
      SPRING_DATASOURCE_PASSWORD: password
      # Variables de entorno para Keycloak - ACTUALIZADO para consistencia
      KEYCLOAK_AUTH_SERVER_URL: http://setcollector-keycloak:8080
      KEYCLOAK_PUBLIC_SERVER_URL: http://localhost:8181
      KEYCLOAK_REALM: setcollector-realm
      KEYCLOAK_RESOURCE: setcollector-backend
      KEYCLOAK_CREDENTIALS_SECRET: Jeq9KKOqImIO7IkaS3CfXpAd3pSjtLQv
      KEYCLOAK_ADMIN_CLIENT_CLIENT_ID: backend-admin-client
      KEYCLOAK_ADMIN_CLIENT_CLIENT_SECRET: nGvEF3wldhQop1KawwbDeplmsFG4aWjk
      # Configuraci贸n de JWT para Spring Security - ACTUALIZADO para consistencia
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://setcollector-keycloak:8080/realms/setcollector-realm
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://setcollector-keycloak:8080/realms/setcollector-realm/protocol/openid-connect/certs
      # Configuraci贸n de logging
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
      LOGGING_LEVEL_COM_SETCOLLECTORMTG: DEBUG
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - keycloak
    networks:
      - setcollector-network

  frontend:
    image: nginx:alpine
    container_name: setcollector-frontend
    volumes:
      - ../frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5173:80"  # Cambiado a puerto no privilegiado
    depends_on:
      - backend
      - keycloak
    networks:
      - setcollector-network

networks:
  setcollector-network:
    driver: bridge

volumes:
  mysql_data: