version: '3.8'
services:
  mysql:
    image: mysql:8.0.42
    container_name: setcollector-mysql
    environment:
      MYSQL_DATABASE: setcollector
      MYSQL_USER: setcollector
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE_KEYCLOAK: keycloak
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - setcollector-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.4
    container_name: setcollector-keycloak
    command: start-dev --import-realm --features=preview
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf
    environment:
      # Configuración de base de datos
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_PORT: 3306
      DB_DATABASE: keycloak
      DB_USER: setcollector
      DB_PASSWORD: password
      # Configuración de admin
      KC_BOOTSTRAP_ADMIN_USERNAME: ADMIN
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      # Configuración simplificada para entorno local
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: "8080"
      KC_HOSTNAME_URL: "http://localhost:8181"
      KC_HOSTNAME_ADMIN_URL: "http://localhost:8181"
      KC_PROXY: "edge"
      KC_CORS: "true"
      KC_CORS_ORIGINS: "*"
      KC_CORS_METHODS: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
      KC_CORS_HEADERS: "*"
      KC_CORS_EXPOSED_HEADERS: "*"
      KC_CORS_ALLOW_CREDENTIALS: "true"
    ports:
      - "8181:8080"
    depends_on:
      - mysql
    networks:
      - setcollector-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    image: eclipse-temurin:21-jre-jammy
    container_name: setcollector-backend
    volumes:
      - ../backend/target/setcollectormtg-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    command: java -jar app.jar
    environment:
      # Configuración simplificada para MySQL
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/setcollector?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: setcollector
      SPRING_DATASOURCE_PASSWORD: password
      # Configuración de Keycloak - URLs internas para comunicación entre contenedores
      KEYCLOAK_AUTH_SERVER_URL: http://setcollector-keycloak:8080
      KEYCLOAK_REALM: setcollector-realm
      KEYCLOAK_RESOURCE: setcollector-backend
      KEYCLOAK_CREDENTIALS_SECRET: Jeq9KKOqImIO7IkaS3CfXpAd3pSjtLQv
      KEYCLOAK_ADMIN_CLIENT_CLIENT_ID: backend-admin-client
      KEYCLOAK_ADMIN_CLIENT_CLIENT_SECRET: nGvEF3wldhQop1KawwbDeplmsFG4aWjk
      # Configuración JWT para Spring Security
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://setcollector-keycloak:8080/realms/setcollector-realm
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://setcollector-keycloak:8080/realms/setcollector-realm/protocol/openid-connect/certs
      # Configuración de logs más simplificada
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_COM_SETCOLLECTORMTG: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: INFO
      # Activar propiedades CORS en Spring Boot
      SPRING_WEB_CORS_ALLOWED_ORIGINS: "*"
      SPRING_WEB_CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
      SPRING_WEB_CORS_ALLOWED_HEADERS: "*"
      SPRING_WEB_CORS_ALLOW_CREDENTIALS: "true"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - keycloak
    networks:
      - setcollector-network

  frontend:
    image: nginx:alpine
    container_name: setcollector-frontend
    volumes:
      - ../frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5173:80"
    depends_on:
      - backend
      - keycloak
    networks:
      - setcollector-network

networks:
  setcollector-network:
    driver: bridge

volumes:
  mysql_data: